In [691]:
# import pytorch
import torch
import torch.nn as nn

In [692]:
x = torch.randn(2, 3)
print(x)

tensor([[-1.1776,  0.0508, -2.8327],
        [ 0.5796, -0.0609,  0.9970]])


In [693]:
x = torch.tensor([[99, 99, 99]], dtype=torch.float32)
print(x.shape)

torch.Size([1, 3])


In [694]:
z = x + x
print(z)

tensor([[198., 198., 198.]])


In [695]:
x.add(x)

tensor([[198., 198., 198.]])

In [696]:
print(x)

tensor([[99., 99., 99.]])


In [697]:
x.add_(x) # In-place addition
print(x)

tensor([[198., 198., 198.]])


In [698]:
y = torch.rand(1, 3).flatten()
y

tensor([0.3081, 0.5938, 0.7304])

In [699]:
z = torch.randint(0, 10, (1,), requires_grad=True, dtype=torch.float16)
print(z)

tensor([3.], dtype=torch.float16, requires_grad=True)


In [700]:
z = torch.randint(0, 10, (1, 9), dtype=torch.float16).clone().detach().requires_grad_()
loss = z.sum()
print("z:", z)
loss.backward()
print("z.grad:", z.grad)


z: tensor([[8., 7., 3., 5., 7., 3., 6., 8., 9.]], dtype=torch.float16,
       requires_grad=True)
z.grad: tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=torch.float16)


In [701]:
x = torch.tensor([0.5,2.1,3.2], dtype=torch.float32, requires_grad=True)
z = torch.tensor([0.1,1.0,0.001], dtype=torch.float32)
x.backward(z) # This computes the gradient of x with respect to z
print(x.grad)

tensor([0.1000, 1.0000, 0.0010])


In [702]:
# This code snippet demonstrates basic tensor operations in PyTorch, including creation, manipulation, and gradient computation.
# It covers tensor addition, in-place operations, random tensor generation, and gradient calculation using the backward method.
# The code also illustrates how to set up tensors with specific data types and gradient requirements.
# The final output will show the gradients computed for the tensor `x` based on the operations performed.
X = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
print(X)


tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [703]:
Y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32,  requires_grad=True)
Z = X + Y
print(Z)


tensor([[ 6.,  8.],
        [10., 12.]], grad_fn=<AddBackward0>)


In [704]:
# The above code initializes two tensors `X` and `Y`, performs element-wise addition, and prints the result.
# It demonstrates basic tensor operations in PyTorch, including tensor creation and arithmetic operations.
# The final output will show the result of the addition of tensors `X` and `Y`.
Z.backward(Y)  # This computes the gradient of Z with respect to X and Y
print(X.grad)  # Prints the gradient of X

tensor([[5., 6.],
        [7., 8.]])


# Deep Nueral Network (Basic)

In [705]:
# dataset for training leaf length with age
# iris dataset 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import torch

In [706]:
data = load_iris()
x = data.data[:, 0]
y = data.data[:, 1]

In [707]:
# x and y as dummy dataset
x = torch.tensor(x, dtype = torch.float32).reshape(-1,1) # Input feature
y = torch.tensor(y, dtype = torch.float32).reshape(-1,1) # Target variable
# Initialize weights and bias
w = torch.randn((1,3), requires_grad=True)  # Weight
b = torch.tensor(0.1, requires_grad=True)  # Bias

In [708]:
# complete training looop

print("w:", w)
print("b:", b)
learning_rate = 0.1
epochs = 12
for epoch in range(epochs):  # Example: 100 epochs
    # forward pass
    y_pred = x @ w + b
    loss = (y_pred - y).pow(2).sum()  # Mean Squared Error

    # backward pass
    loss.backward()  # Compute gradients

    # update weights
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad        



w: tensor([[-0.6597, -1.1718,  0.6925]], requires_grad=True)
b: tensor(0.1000, requires_grad=True)


In [709]:
print("w:", w)
print("b:", b)

w: tensor([[-4.0080e+36, -4.8553e+36, -1.7707e+36]], requires_grad=True)
b: tensor(-1.7870e+36, requires_grad=True)


In [710]:
i = torch.tensor([11.2], dtype=torch.float32)  # Example input
i * w + b
# This code snippet demonstrates a basic implementation of a deep neural network using PyTorc

tensor([[-4.6677e+37, -5.6166e+37, -2.1619e+37]], grad_fn=<AddBackward0>)

# Gradient Descent

## Linear Regression with PyTorch

In [711]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 10, 15, 20, 25])
w = 0.01
b = 0.01
def forward(x, w, b):
    return x * w + b
def gradient(x, y, w, b, error):
    return (2/ len(x)) * np.dot(x.T, (error)), (2 / len(x)) * np.sum(error)
                                
def backward(x, y, w, b):
    y_pred = forward(x, w, b)
    error = y_pred - y
    grad_w, grad_b = gradient(x, y, w, b, error)
    return grad_w, grad_b

def loss(y_pred, y):
    return np.mean((y_pred - y) ** 2)  # Mean Squared Error
def update(w, b, grad_w, grad_b, learning_rate):
    w -= learning_rate * grad_w
    b -= learning_rate * grad_b
    return w, b


In [712]:
lr = 0.035
lossi = 1000
epochs = 100
for i in range(epochs):
    y_pred = forward(x, w, b)
    lossi = loss(y_pred, y)
    grad_w, grad_b = backward(x, y, w, b)
    w, b = update(w, b, grad_w, grad_b, lr)
    grad_b, grad_w = None, None  # Reset gradients to avoid accumulation
    if i % 11 == 0:  # Print every 10 epochs
        print(f"Epoch {i}, Loss: {lossi}, w: {w}, b: {b}")

Epoch 0, Loss: 273.6018, w: 3.8502000000000005, b: 1.0572000000000001
Epoch 11, Loss: 0.23417665823648784, w: 4.689544004027669, b: 1.1208446406827095
Epoch 22, Loss: 0.18022194581278253, w: 4.727647050596297, b: 0.9832805644702476
Epoch 33, Loss: 0.13869849368055148, w: 4.761073611898107, b: 0.8626000719802476
Epoch 44, Loss: 0.10674211768436859, w: 4.790397647404217, b: 0.7567309993371104
Epoch 55, Loss: 0.08214854671735519, w: 4.81612267040612, b: 0.6638555037946418
Epoch 66, Loss: 0.06322137759837342, w: 4.838690396744829, b: 0.582378851011113
Epoch 77, Loss: 0.04865506141195945, w: 4.85848832936713, b: 0.5109020323946012
Epoch 88, Loss: 0.03744485000058698, w: 4.875856412010214, b: 0.4481977431902885
Epoch 99, Loss: 0.028817490942921475, w: 4.891092866262876, b: 0.3931893088374225


In [713]:
print(f"Prediction before training: {forward(x, 0.1, 0.1)}")
print(f"Prediction after training: {forward(x, w, b)}")
print("Original y:", y)

Prediction before training: [0.2 0.3 0.4 0.5 0.6]
Prediction after training: [ 5.28428218 10.17537504 15.06646791 19.95756077 24.84865364]
Original y: [ 5 10 15 20 25]


In [714]:
# using pytorch to
# design the model
# training loop:
## forward pass
## backward pass
## update weights

In [715]:
x = torch.tensor(x, dtype = torch.float32).reshape(-1,1) # Input feature
y = torch.tensor(y, dtype = torch.float32).reshape(-1,1) #
# Target variable
w = torch.randn((1,1), requires_grad=True)  # Weight
b = torch.tensor(0.1, requires_grad=True)  # Bias
def forward(x, w, b):
    return x * w + b
def loss(y_pred, y):
    #return torch.mean((y_pred - y) ** 2)  # Mean Squared Error
    # mse in pytorch
    return torch.nn.functional.mse_loss(y_pred, y)  # Mean Squared Error

def gradient(x, y, w, b, error):

    grad_w = (2 / len(x)) * torch.matmul(x.T, error)
    grad_b = (2 / len(x)) * torch.sum(error)
    return grad_w, grad_b
def backward(x, y, w, b):
    y_pred = forward(x, w, b)
    error = y_pred - y
    grad_w, grad_b = gradient(x, y, w, b, error)
    return grad_w, grad_b
def update(w, b, learning_rate):
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        #b.grad.zero_()  # Reset gradients to avoid accumulation
        w.grad.zero_()  
    return w, b
# loop for 100 epochs and 0.035 learning rate
lr = 0.01
for i in range(100):
    y_pred = forward(x, w, b)
    lossi = loss(y_pred, y)
    #grad_w, grad_b = backward(x, y, w, b)
    lossi.backward()  # Compute gradients
    
    w, b = update(w, b, lr)
    if i % 11 == 0:  # Print every 10 epochs
        print(f"Epoch {i}, Loss: {lossi.item()}, w: {w.item()}, b: {b.item()}")

Epoch 0, Loss: 391.28106689453125, w: 0.32070648670196533, b: 0.4574841260910034
Epoch 11, Loss: 25.021488189697266, w: 2.813230514526367, b: 11.001218795776367
Epoch 22, Loss: 38.059715270996094, w: 1.2955565452575684, b: 14.211529731750488
Epoch 33, Loss: 22.75455093383789, w: 1.7500704526901245, b: 10.085675239562988
Epoch 44, Loss: 8.627947807312012, w: 3.1246511936187744, b: 4.7999348640441895
Epoch 55, Loss: 2.0218987464904785, w: 4.289093494415283, b: 1.2847983837127686
Epoch 66, Loss: 0.31056472659111023, w: 4.91710090637207, b: -0.24855896830558777
Epoch 77, Loss: 0.07183408737182617, w: 5.1276068687438965, b: -0.5677484273910522
Epoch 88, Loss: 0.03685746341943741, w: 5.130650043487549, b: -0.4091895818710327
Epoch 99, Loss: 0.013973020017147064, w: 5.0744428634643555, b: -0.18609121441841125


In [716]:
print(f"prediction before training: {forward(x, 0.1, 0.1)}")
print(f"Prediction after training: {forward(x, w, b)}")
print("Original y:", y)

prediction before training: tensor([[0.2000],
        [0.3000],
        [0.4000],
        [0.5000],
        [0.6000]])
Prediction after training: tensor([[ 4.8884],
        [ 9.9628],
        [15.0372],
        [20.1117],
        [25.1861]], grad_fn=<AddBackward0>)
Original y: tensor([[ 5.],
        [10.],
        [15.],
        [20.],
        [25.]])


## Logistic Regression with PyTorch using ANN

In [ ]:
# designing an ANN for logistic regression
import torch
import torch.nn as nn
import torch.optim as optim
class LogisticRegressionModel(nn.Module):
    def __init__(self, input_size):
        super(LogisticRegressionModel, self).__init__()
        self.linear = nn.Linear(input_size, 1)  # Single output for binary classification

    def forward(self, x):
        
        return torch.sigmoid(self.linear(x))  # Sigmoid activation for binary classification
# Example usage
input_size = 1  # Number of input features
model = LogisticRegressionModel(input_size)
# Define loss function and optimizer
criterion = nn.BCELoss()  # Binary Cross-Entropy Loss
optimizer = optim.SGD(model.parameters(), lr=0.01)  # Stochastic Gradient


In [733]:
# Descent optimizer
# Dummy dataset
x = torch.tensor([[9.0], [2.0], [3.0], [0.5], [5.0]], dtype=torch.float32)  # Input features
y = torch.tensor([[0.0], [0.0], [1.0], [0.0], [1.0]], dtype=torch.float32)  # Target labels
# Training loop
num_epochs = 100
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(x)
    loss = criterion(outputs, y)  # Compute loss
    # Backward pass and optimization
    optimizer.zero_grad()  # Zero the gradients
    loss.backward()  # Backpropagation
    optimizer.step()  # Update weights
    if (epoch+1) % 10 == 0:  # Print every 10 epochs
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')


Epoch [10/100], Loss: 0.6760
Epoch [20/100], Loss: 0.6756
Epoch [30/100], Loss: 0.6755
Epoch [40/100], Loss: 0.6754
Epoch [50/100], Loss: 0.6753
Epoch [60/100], Loss: 0.6753
Epoch [70/100], Loss: 0.6752
Epoch [80/100], Loss: 0.6752
Epoch [90/100], Loss: 0.6751
Epoch [100/100], Loss: 0.6751


In [734]:

# Example prediction
with torch.no_grad():
    test_input = torch.tensor([[6.0]], dtype=torch.float32)  # New input for prediction
    predicted = model(test_input)
    print(f'Predicted probability for input {test_input.item()}: {predicted.item():.4f}')
# This code implements a simple logistic regression model using PyTorch.
# It defines a neural network with a single linear layer and a sigmoid activation function.

Predicted probability for input 6.0: 0.4100


In [735]:
torch.tensor([[6.0]], dtype=torch.float32)

tensor([[6.]])