In [436]:
# import pytorch
import torch
import torch.nn as nn

In [437]:
x = torch.randn(2, 3)
print(x)

tensor([[-1.5212, -0.0373, -1.6945],
        [ 0.1071, -0.1971,  0.1653]])


In [438]:
x = torch.tensor([[99, 99, 99]], dtype=torch.float32)
print(x.shape)

torch.Size([1, 3])


In [439]:
z = x + x
print(z)

tensor([[198., 198., 198.]])


In [440]:
x.add(x)

tensor([[198., 198., 198.]])

In [441]:
print(x)

tensor([[99., 99., 99.]])


In [442]:
x.add_(x) # In-place addition
print(x)

tensor([[198., 198., 198.]])


In [443]:
y = torch.rand(1, 3).flatten()
y

tensor([0.2489, 0.1046, 0.4835])

In [444]:
z = torch.randint(0, 10, (1,), requires_grad=True, dtype=torch.float16)
print(z)

tensor([5.], dtype=torch.float16, requires_grad=True)


In [445]:
z = torch.randint(0, 10, (1, 9), dtype=torch.float16).clone().detach().requires_grad_()
loss = z.sum()
print("z:", z)
loss.backward()
print("z.grad:", z.grad)


z: tensor([[2., 8., 5., 6., 3., 5., 5., 7., 1.]], dtype=torch.float16,
       requires_grad=True)
z.grad: tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=torch.float16)


In [446]:
x = torch.tensor([0.5,2.1,3.2], dtype=torch.float32, requires_grad=True)
z = torch.tensor([0.1,1.0,0.001], dtype=torch.float32)
x.backward(z) # This computes the gradient of x with respect to z
print(x.grad)

tensor([0.1000, 1.0000, 0.0010])


In [447]:
# This code snippet demonstrates basic tensor operations in PyTorch, including creation, manipulation, and gradient computation.
# It covers tensor addition, in-place operations, random tensor generation, and gradient calculation using the backward method.
# The code also illustrates how to set up tensors with specific data types and gradient requirements.
# The final output will show the gradients computed for the tensor `x` based on the operations performed.
X = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
print(X)


tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [448]:
Y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32,  requires_grad=True)
Z = X + Y
print(Z)


tensor([[ 6.,  8.],
        [10., 12.]], grad_fn=<AddBackward0>)


In [449]:
# The above code initializes two tensors `X` and `Y`, performs element-wise addition, and prints the result.
# It demonstrates basic tensor operations in PyTorch, including tensor creation and arithmetic operations.
# The final output will show the result of the addition of tensors `X` and `Y`.
Z.backward(Y)  # This computes the gradient of Z with respect to X and Y
print(X.grad)  # Prints the gradient of X

tensor([[5., 6.],
        [7., 8.]])


# Deep Nueral Network (Basic)

In [450]:
# dataset for training leaf length with age
# iris dataset 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import torch

In [451]:
data = load_iris()
x = data.data[:, 0]
y = data.data[:, 1]

In [452]:
# x and y as dummy dataset
x = torch.tensor(x, dtype = torch.float32).reshape(-1,1) # Input feature
y = torch.tensor(y, dtype = torch.float32).reshape(-1,1) # Target variable
# Initialize weights and bias
w = torch.randn((1,3), requires_grad=True)  # Weight
b = torch.tensor(0.1, requires_grad=True)  # Bias

In [453]:
# complete training looop

print("w:", w)
print("b:", b)
learning_rate = 0.1
epochs = 12
for epoch in range(epochs):  # Example: 100 epochs
    # forward pass
    y_pred = x @ w + b
    loss = (y_pred - y).pow(2).sum()  # Mean Squared Error

    # backward pass
    loss.backward()  # Compute gradients

    # update weights
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad        



w: tensor([[ 0.8065,  0.9200, -1.4817]], requires_grad=True)
b: tensor(0.1000, requires_grad=True)


In [454]:
print("w:", w)
print("b:", b)

w: tensor([[-4.7780e+35, -2.8994e+35, -4.2637e+36]], requires_grad=True)
b: tensor(-8.4554e+35, requires_grad=True)


In [455]:
i = torch.tensor([11.2], dtype=torch.float32)  # Example input
i * w + b
# This code snippet demonstrates a basic implementation of a deep neural network using PyTorc

tensor([[-6.1969e+36, -4.0928e+36, -4.8599e+37]], grad_fn=<AddBackward0>)

# Gradient Descent

## Linear Regression with PyTorch

In [464]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 10, 15, 20, 25])
w = 0.1
b = 0.1
def forward(x, w, b):
    return x * w + b
def gradient(x, y, w, b, error):
    return (2/ len(x)) * np.dot(x.T, (error)), (2 / len(x)) * np.sum(error)
                                
def backward(x, y, w, b):
    y_pred = forward(x, w, b)
    error = y_pred - y
    grad_w, grad_b = gradient(x, y, w, b, error)
    return grad_w, grad_b

def loss(y_pred, y):
    return np.mean((y_pred - y) ** 2)  # Mean Squared Error
def update(w, b, grad_w, grad_b, learning_rate):
    w -= learning_rate * grad_w
    b -= learning_rate * grad_b
    return w, b


In [467]:
lr = 0.035
lossi = 1000
epochs = 100
for i in range(epochs):
    y_pred = forward(x, w, b)
    lossi = loss(y_pred, y)
    grad_w, grad_b = backward(x, y, w, b)
    w, b = update(w, b, grad_w, grad_b, lr)
    if i % 11 == 0:  # Print every 10 epochs
        print(f"Epoch {i}, Loss: {lossi}, w: {w}, b: {b}")

Epoch 0, Loss: 0.030831565637859538, w: 4.887351338689334, b: 0.4066974105581815
Epoch 11, Loss: 0.023727918886340495, w: 4.901176991729303, b: 0.35678241622793994
Epoch 22, Loss: 0.018260964794645704, w: 4.913305787658343, b: 0.3129936144779968
Epoch 33, Loss: 0.014053606505846802, w: 4.923945986010133, b: 0.2745791223113789
Epoch 44, Loss: 0.010815630939669437, w: 4.933280286102888, b: 0.24087933721915356
Epoch 55, Loss: 0.008323690618096348, w: 4.941468964108777, b: 0.211315611364434
Epoch 66, Loss: 0.006405897713434869, w: 4.948652625102939, b: 0.18538031581221864
Epoch 77, Loss: 0.004929967654705583, w: 4.954954617346612, b: 0.16262812420124817
Epoch 88, Loss: 0.003794094467894744, w: 4.96048315025923, b: 0.14266836619270326
Epoch 99, Loss: 0.0029199284538041588, w: 4.9653331524464885, b: 0.12515831939933972


In [468]:
print(f"Prediction before training: {forward(x, 0.1, 0.1)}")
print(f"Prediction after training: {forward(x, w, b)}")
print("Original y:", y)

Prediction before training: [0.2 0.3 0.4 0.5 0.6]
Prediction after training: [ 5.09049147 10.05582462 15.02115778 19.98649093 24.95182408]
Original y: [ 5 10 15 20 25]


In [471]:
# using pytorch to
# design the model
# training loop:
## forward pass
## backward pass
## update weights

In [473]:
x = torch.tensor(x, dtype = torch.float32).reshape(-1,1) # Input feature
y = torch.tensor(y, dtype = torch.float32).reshape(-1,1) #
# Target variable
w = torch.randn((1,1), requires_grad=True)  # Weight
b = torch.tensor(0.1, requires_grad=True)  # Bias
def forward(x, w, b):
    return x @ w + b
def loss(y_pred, y):
    return torch.mean((y_pred - y) ** 2)  # Mean Squared Error
def gradient(x, y, w, b, error):
    grad_w = (2 / len(x)) * torch.matmul(x.T, error)
    grad_b = (2 / len(x)) * torch.sum(error)
    return grad_w, grad_b
def backward(x, y, w, b):
    y_pred = forward(x, w, b)
    error = y_pred - y
    grad_w, grad_b = gradient(x, y, w, b, error)
    return grad_w, grad_b
def update(w, b, grad_w, grad_b, learning_rate):
    with torch.no_grad():
        w -= learning_rate * grad_w
        b -= learning_rate * grad_b
    return w, b
# loop for 100 epochs and 0.035 learning rate
for i in range(100):
    y_pred = forward(x, w, b)
    lossi = loss(y_pred, y)
    grad_w, grad_b = backward(x, y, w, b)
    w, b = update(w, b, grad_w, grad_b, 0.035)
    if i % 11 == 0:  # Print every 10 epochs
        print(f"Epoch {i}, Loss: {lossi.item()}, w: {w.item()}, b: {b.item()}")

Epoch 0, Loss: 178.27908325195312, w: 4.046794414520264, b: 0.9441442489624023
Epoch 11, Loss: 0.18061980605125427, w: 4.727346420288086, b: 0.9843649864196777
Epoch 22, Loss: 0.13900470733642578, w: 4.760810375213623, b: 0.8635513782501221
Epoch 33, Loss: 0.10697754472494125, w: 4.79016637802124, b: 0.7575653791427612
Epoch 44, Loss: 0.0823298841714859, w: 4.815919876098633, b: 0.6645876169204712
Epoch 55, Loss: 0.06336110085248947, w: 4.838512420654297, b: 0.5830211639404297
Epoch 66, Loss: 0.04876245558261871, w: 4.85833215713501, b: 0.5114653706550598
Epoch 77, Loss: 0.03752750903367996, w: 4.8757195472717285, b: 0.44869208335876465
Epoch 88, Loss: 0.028881078585982323, w: 4.89097261428833, b: 0.393623024225235
Epoch 99, Loss: 0.02222689799964428, w: 4.904354095458984, b: 0.34531277418136597


C:\Users\AB\AppData\Local\Temp\ipykernel_13596\582390938.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype = torch.float32).reshape(-1,1) # Input feature
C:\Users\AB\AppData\Local\Temp\ipykernel_13596\582390938.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y, dtype = torch.float32).reshape(-1,1) #
