In [436]:
# import pytorch
import torch
import torch.nn as nn

In [437]:
x = torch.randn(2, 3)
print(x)

tensor([[-1.5212, -0.0373, -1.6945],
        [ 0.1071, -0.1971,  0.1653]])


In [438]:
x = torch.tensor([[99, 99, 99]], dtype=torch.float32)
print(x.shape)

torch.Size([1, 3])


In [439]:
z = x + x
print(z)

tensor([[198., 198., 198.]])


In [440]:
x.add(x)

tensor([[198., 198., 198.]])

In [441]:
print(x)

tensor([[99., 99., 99.]])


In [442]:
x.add_(x) # In-place addition
print(x)

tensor([[198., 198., 198.]])


In [443]:
y = torch.rand(1, 3).flatten()
y

tensor([0.2489, 0.1046, 0.4835])

In [444]:
z = torch.randint(0, 10, (1,), requires_grad=True, dtype=torch.float16)
print(z)

tensor([5.], dtype=torch.float16, requires_grad=True)


In [445]:
z = torch.randint(0, 10, (1, 9), dtype=torch.float16).clone().detach().requires_grad_()
loss = z.sum()
print("z:", z)
loss.backward()
print("z.grad:", z.grad)


z: tensor([[2., 8., 5., 6., 3., 5., 5., 7., 1.]], dtype=torch.float16,
       requires_grad=True)
z.grad: tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=torch.float16)


In [446]:
x = torch.tensor([0.5,2.1,3.2], dtype=torch.float32, requires_grad=True)
z = torch.tensor([0.1,1.0,0.001], dtype=torch.float32)
x.backward(z) # This computes the gradient of x with respect to z
print(x.grad)

tensor([0.1000, 1.0000, 0.0010])


In [447]:
# This code snippet demonstrates basic tensor operations in PyTorch, including creation, manipulation, and gradient computation.
# It covers tensor addition, in-place operations, random tensor generation, and gradient calculation using the backward method.
# The code also illustrates how to set up tensors with specific data types and gradient requirements.
# The final output will show the gradients computed for the tensor `x` based on the operations performed.
X = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
print(X)


tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [448]:
Y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32,  requires_grad=True)
Z = X + Y
print(Z)


tensor([[ 6.,  8.],
        [10., 12.]], grad_fn=<AddBackward0>)


In [449]:
# The above code initializes two tensors `X` and `Y`, performs element-wise addition, and prints the result.
# It demonstrates basic tensor operations in PyTorch, including tensor creation and arithmetic operations.
# The final output will show the result of the addition of tensors `X` and `Y`.
Z.backward(Y)  # This computes the gradient of Z with respect to X and Y
print(X.grad)  # Prints the gradient of X

tensor([[5., 6.],
        [7., 8.]])


# Deep Nueral Network (Basic)

In [450]:
# dataset for training leaf length with age
# iris dataset 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import torch

In [451]:
data = load_iris()
x = data.data[:, 0]
y = data.data[:, 1]

In [452]:
# x and y as dummy dataset
x = torch.tensor(x, dtype = torch.float32).reshape(-1,1) # Input feature
y = torch.tensor(y, dtype = torch.float32).reshape(-1,1) # Target variable
# Initialize weights and bias
w = torch.randn((1,3), requires_grad=True)  # Weight
b = torch.tensor(0.1, requires_grad=True)  # Bias

In [453]:
# complete training looop

print("w:", w)
print("b:", b)
learning_rate = 0.1
epochs = 12
for epoch in range(epochs):  # Example: 100 epochs
    # forward pass
    y_pred = x @ w + b
    loss = (y_pred - y).pow(2).sum()  # Mean Squared Error

    # backward pass
    loss.backward()  # Compute gradients

    # update weights
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad        



w: tensor([[ 0.8065,  0.9200, -1.4817]], requires_grad=True)
b: tensor(0.1000, requires_grad=True)


In [454]:
print("w:", w)
print("b:", b)

w: tensor([[-4.7780e+35, -2.8994e+35, -4.2637e+36]], requires_grad=True)
b: tensor(-8.4554e+35, requires_grad=True)


In [455]:
i = torch.tensor([11.2], dtype=torch.float32)  # Example input
i * w + b
# This code snippet demonstrates a basic implementation of a deep neural network using PyTorc

tensor([[-6.1969e+36, -4.0928e+36, -4.8599e+37]], grad_fn=<AddBackward0>)

# Gradient Descent

## Linear Regression with PyTorch

In [456]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 10, 15, 20, 25])
w = 0.1
b = 0.1
def forward(x, w, b):
    return x * w + b
def backward(x, y, w, b):
    y_pred = forward(x, w, b)
    error = y_pred - y
    grad_w = (2 / len(x)) * np.dot(x.T, (error))  # Gradient w.r.t. weights 
    grad_b = (2 / len(x)) * np.sum(error)  # Gradient w.r.t. bias
    return grad_w, grad_b
def loss(y_pred, y):
    return np.mean((y_pred - y) ** 2)  # Mean Squared Error
def update(w, b, grad_w, grad_b, learning_rate):
    w -= learning_rate * grad_w
    b -= learning_rate * grad_b
    return w, b


In [457]:
lr = 0.035
lossi = 1000
epochs = 100
for i in range(epochs):
    y_pred = forward(x, w, b)
    lossi = loss(y_pred, y)
    grad_w, grad_b = backward(x, y, w, b)
    w, b = update(w, b, grad_w, grad_b, lr)
    if i % 1 == 0:  # Print every 10 epochs
        print(f"Epoch {i}, Loss: {lossi}, w: {w}, b: {b}")

Epoch 0, Loss: 261.17999999999995, w: 3.8520000000000008, b: 1.1220000000000003
Epoch 1, Loss: 8.027491999999981, w: 4.5003400000000005, b: 1.2845400000000002
Epoch 2, Loss: 0.5453047447999986, w: 4.6153248, b: 1.2995508000000002
Epoch 3, Loss: 0.3171276028251209, w: 4.638619036, b: 1.2893640360000003
Epoch 4, Loss: 0.3033081202278067, w: 4.64611593072, b: 1.2749985559200003
Epoch 5, Loss: 0.2959845332194163, w: 4.6508569673224, b: 1.2600643115544004
Epoch 6, Loss: 0.28901544856399936, w: 4.655083597057728, b: 1.2451798466078883
Epoch 7, Loss: 0.2822157033542196, w: 4.6591814595356205, b: 1.2304497019632132
Epoch 8, Loss: 0.27557609260073035, w: 4.663217298280918, b: 1.215890116323308
Epoch 9, Loss: 0.2690926947085977, w: 4.667203054176716, b: 1.2015021755416837
Epoch 10, Loss: 0.2627618299519414, w: 4.671141245596891, b: 1.1872843818766554
Epoch 11, Loss: 0.2565799095941068, w: 4.675032766293187, b: 1.1732348135699424
Epoch 12, Loss: 0.25054342946002506, w: 4.678878225397745, b: 1.159

In [458]:
print(f"Prediction before training: {forward(x, 0.1, 0.1)}")
print(f"Prediction after training: {forward(x, w, b)}")
print("Original y:", y)

Prediction before training: [0.2 0.3 0.4 0.5 0.6]
Prediction after training: [ 5.29757    10.18357237 15.06957473 19.95557709 24.84157946]
Original y: [ 5 10 15 20 25]
