In [89]:
# import pytorch
import torch
import torch.nn as nn

In [90]:
x = torch.randn(2, 3)
print(x)

tensor([[ 0.7696, -0.5084, -0.1536],
        [-1.1830, -0.7204,  0.0146]])


In [91]:
x = torch.tensor([[99, 99, 99]], dtype=torch.float32)
print(x.shape)

torch.Size([1, 3])


In [92]:
z = x + x
print(z)

tensor([[198., 198., 198.]])


In [93]:
x.add(x)

tensor([[198., 198., 198.]])

In [94]:
print(x)

tensor([[99., 99., 99.]])


In [95]:
x.add_(x) # In-place addition
print(x)

tensor([[198., 198., 198.]])


In [96]:
y = torch.rand(1, 3).flatten()
y

tensor([0.4574, 0.4267, 0.1919])

In [97]:
z = torch.randint(0, 10, (1,), requires_grad=True, dtype=torch.float16)
print(z)

tensor([4.], dtype=torch.float16, requires_grad=True)


In [98]:
z = torch.randint(0, 10, (1, 9), dtype=torch.float16).clone().detach().requires_grad_()
loss = z.sum()
print("z:", z)
loss.backward()
print("z.grad:", z.grad)


z: tensor([[4., 2., 9., 5., 3., 4., 8., 2., 5.]], dtype=torch.float16,
       requires_grad=True)
z.grad: tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=torch.float16)


In [99]:
x = torch.tensor([0.5,2.1,3.2], dtype=torch.float32, requires_grad=True)
z = torch.tensor([0.1,1.0,0.001], dtype=torch.float32)
x.backward(z) # This computes the gradient of x with respect to z
print(x.grad)

tensor([0.1000, 1.0000, 0.0010])


In [100]:
# This code snippet demonstrates basic tensor operations in PyTorch, including creation, manipulation, and gradient computation.
# It covers tensor addition, in-place operations, random tensor generation, and gradient calculation using the backward method.
# The code also illustrates how to set up tensors with specific data types and gradient requirements.
# The final output will show the gradients computed for the tensor `x` based on the operations performed.
X = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
print(X)


tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [101]:
Y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32,  requires_grad=True)
Z = X + Y
print(Z)


tensor([[ 6.,  8.],
        [10., 12.]], grad_fn=<AddBackward0>)


In [102]:
# The above code initializes two tensors `X` and `Y`, performs element-wise addition, and prints the result.
# It demonstrates basic tensor operations in PyTorch, including tensor creation and arithmetic operations.
# The final output will show the result of the addition of tensors `X` and `Y`.
Z.backward(Y)  # This computes the gradient of Z with respect to X and Y
print(X.grad)  # Prints the gradient of X

tensor([[5., 6.],
        [7., 8.]])


# Deep Nueral Network (Basic)

In [103]:
# dataset for training leaf length with age
# iris dataset 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import torch

In [104]:
data = load_iris()
x = data.data[:, 0]
y = data.data[:, 1]

In [105]:
# x and y as dummy dataset
x = torch.tensor(x, dtype = torch.float32).reshape(-1,1) # Input feature
y = torch.tensor(y, dtype = torch.float32).reshape(-1,1) # Target variable
# Initialize weights and bias
w = torch.randn((1,3), requires_grad=True)  # Weight
b = torch.tensor(0.1, requires_grad=True)  # Bias

# Back Propagation

```python

In [106]:
# complete training looop

print("w:", w)
print("b:", b)
learning_rate = 0.1
epochs = 12
for epoch in range(epochs):  # Example: 100 epochs
    # forward pass
    y_pred = x @ w + b
    loss = (y_pred - y).pow(2).sum()  # Mean Squared Error

    # backward pass
    loss.backward()  # Compute gradients

    # update weights
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad        



w: tensor([[-0.6441,  0.9284,  1.0247]], requires_grad=True)
b: tensor(0.1000, requires_grad=True)


In [107]:
print("w:", w)
print("b:", b)

w: tensor([[-2.0286e+36,  5.7320e+35,  7.3249e+35]], requires_grad=True)
b: tensor(-1.2148e+35, requires_grad=True)


In [108]:
i = torch.tensor([11.2], dtype=torch.float32)  # Example input
i * w + b
# This code snippet demonstrates a basic implementation of a deep neural network using PyTorc

tensor([[-2.2842e+37,  6.2984e+36,  8.0825e+36]], grad_fn=<AddBackward0>)

# Gradient Descent

## Linear Regression with PyTorch

In [109]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 10, 15, 20, 25])
w = 0.01
b = 0.01
def forward(x, w, b):
    return x * w + b
def gradient(x, y, w, b, error):
    return (2/ len(x)) * np.dot(x.T, (error)), (2 / len(x)) * np.sum(error)
                                
def backward(x, y, w, b):
    y_pred = forward(x, w, b)
    error = y_pred - y
    grad_w, grad_b = gradient(x, y, w, b, error)
    return grad_w, grad_b

def loss(y_pred, y):
    return np.mean((y_pred - y) ** 2)  # Mean Squared Error
def update(w, b, grad_w, grad_b, learning_rate):
    w -= learning_rate * grad_w
    b -= learning_rate * grad_b
    return w, b


In [110]:
lr = 0.035
lossi = 1000
epochs = 100
for i in range(epochs):
    y_pred = forward(x, w, b)
    lossi = loss(y_pred, y)
    grad_w, grad_b = backward(x, y, w, b)
    w, b = update(w, b, grad_w, grad_b, lr)
    grad_b, grad_w = None, None  # Reset gradients to avoid accumulation
    if i % 11 == 0:  # Print every 10 epochs
        print(f"Epoch {i}, Loss: {lossi}, w: {w}, b: {b}")

Epoch 0, Loss: 273.6018, w: 3.8502000000000005, b: 1.0572000000000001
Epoch 11, Loss: 0.23417665823648784, w: 4.689544004027669, b: 1.1208446406827095
Epoch 22, Loss: 0.18022194581278253, w: 4.727647050596297, b: 0.9832805644702476
Epoch 33, Loss: 0.13869849368055148, w: 4.761073611898107, b: 0.8626000719802476
Epoch 44, Loss: 0.10674211768436859, w: 4.790397647404217, b: 0.7567309993371104
Epoch 55, Loss: 0.08214854671735519, w: 4.81612267040612, b: 0.6638555037946418
Epoch 66, Loss: 0.06322137759837342, w: 4.838690396744829, b: 0.582378851011113
Epoch 77, Loss: 0.04865506141195945, w: 4.85848832936713, b: 0.5109020323946012
Epoch 88, Loss: 0.03744485000058698, w: 4.875856412010214, b: 0.4481977431902885
Epoch 99, Loss: 0.028817490942921475, w: 4.891092866262876, b: 0.3931893088374225


In [111]:
print(f"Prediction before training: {forward(x, 0.1, 0.1)}")
print(f"Prediction after training: {forward(x, w, b)}")
print("Original y:", y)

Prediction before training: [0.2 0.3 0.4 0.5 0.6]
Prediction after training: [ 5.28428218 10.17537504 15.06646791 19.95756077 24.84865364]
Original y: [ 5 10 15 20 25]


In [112]:
# using pytorch to
# design the model
# training loop:
## forward pass
## backward pass
## update weights

In [113]:
x = torch.tensor(x, dtype = torch.float32).reshape(-1,1) # Input feature
y = torch.tensor(y, dtype = torch.float32).reshape(-1,1) #
# Target variable
w = torch.randn((1,1), requires_grad=True)  # Weight
b = torch.tensor(0.1, requires_grad=True)  # Bias
def forward(x, w, b):
    return x * w + b
def loss(y_pred, y):
    #return torch.mean((y_pred - y) ** 2)  # Mean Squared Error
    # mse in pytorch
    return torch.nn.functional.mse_loss(y_pred, y)  # Mean Squared Error

def gradient(x, y, w, b, error):

    grad_w = (2 / len(x)) * torch.matmul(x.T, error)
    grad_b = (2 / len(x)) * torch.sum(error)
    return grad_w, grad_b
def backward(x, y, w, b):
    y_pred = forward(x, w, b)
    error = y_pred - y
    grad_w, grad_b = gradient(x, y, w, b, error)
    return grad_w, grad_b
def update(w, b, learning_rate):
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        #b.grad.zero_()  # Reset gradients to avoid accumulation
        w.grad.zero_()  
    return w, b
# loop for 100 epochs and 0.035 learning rate
lr = 0.01
for i in range(100):
    y_pred = forward(x, w, b)
    lossi = loss(y_pred, y)
    #grad_w, grad_b = backward(x, y, w, b)
    lossi.backward()  # Compute gradients
    
    w, b = update(w, b, lr)
    if i % 11 == 0:  # Print every 10 epochs
        print(f"Epoch {i}, Loss: {lossi.item()}, w: {w.item()}, b: {b.item()}")

Epoch 0, Loss: 188.93197631835938, w: 1.7401500940322876, b: 0.3482961654663086
Epoch 11, Loss: 12.134425163269043, w: 3.473174810409546, b: 7.667831897735596
Epoch 22, Loss: 18.42071533203125, w: 2.421295166015625, b: 9.887635231018066
Epoch 33, Loss: 11.006176948547363, w: 2.7397100925445557, b: 7.01247501373291
Epoch 44, Loss: 4.170379161834717, w: 3.6964271068573, b: 3.335477113723755
Epoch 55, Loss: 0.9766318202018738, w: 4.50618839263916, b: 0.8917154669761658
Epoch 66, Loss: 0.14996230602264404, w: 4.942668914794922, b: -0.17364393174648285
Epoch 77, Loss: 0.03473499044775963, w: 5.088850975036621, b: -0.39499926567077637
Epoch 88, Loss: 0.01782500557601452, w: 5.090860366821289, b: -0.28448429703712463
Epoch 99, Loss: 0.0067533464170992374, w: 5.051741600036621, b: -0.1292993575334549


In [114]:
print(f"prediction before training: {forward(x, 0.1, 0.1)}")
print(f"Prediction after training: {forward(x, w, b)}")
print("Original y:", y)

prediction before training: tensor([[0.2000],
        [0.3000],
        [0.4000],
        [0.5000],
        [0.6000]])
Prediction after training: tensor([[ 4.9224],
        [ 9.9742],
        [15.0259],
        [20.0777],
        [25.1294]], grad_fn=<AddBackward0>)
Original y: tensor([[ 5.],
        [10.],
        [15.],
        [20.],
        [25.]])


## Logistic Regression with PyTorch using ANN

In [115]:
# designing an ANN for logistic regression
import torch
import torch.nn as nn
import torch.optim as optim
class LogisticRegressionModel(nn.Module):
    def __init__(self, input_size):
        super(LogisticRegressionModel, self).__init__()
        self.linear = nn.Linear(input_size, 1)  # Single output for binary classification

    def forward(self, x):
        
        return torch.sigmoid(self.linear(x))  # Sigmoid activation for binary classification
# Example usage
input_size = 1  # Number of input features
model = LogisticRegressionModel(input_size)
# Define loss function and optimizer
criterion = nn.BCELoss()  # Binary Cross-Entropy Loss
optimizer = optim.SGD(model.parameters(), lr=0.01)  # Stochastic Gradient


In [116]:
# Descent optimizer
# Dummy dataset
x = torch.tensor([[9.0], [2.0], [3.0], [0.5], [5.0]], dtype=torch.float32)  # Input features
y = torch.tensor([[0.0], [0.0], [1.0], [0.0], [1.0]], dtype=torch.float32)  # Target labels
# Training loop
num_epochs = 100
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(x)
    loss = criterion(outputs, y)  # Compute loss
    # Backward pass and optimization
    optimizer.zero_grad()  # Zero the gradients
    loss.backward()  # Backpropagation
    optimizer.step()  # Update weights
    if (epoch+1) % 10 == 0:  # Print every 10 epochs
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')


Epoch [10/100], Loss: 1.3751
Epoch [20/100], Loss: 1.1687
Epoch [30/100], Loss: 0.9889
Epoch [40/100], Loss: 0.8471
Epoch [50/100], Loss: 0.7530
Epoch [60/100], Loss: 0.7038
Epoch [70/100], Loss: 0.6835
Epoch [80/100], Loss: 0.6764
Epoch [90/100], Loss: 0.6741
Epoch [100/100], Loss: 0.6734


In [117]:

# Example prediction
with torch.no_grad():
    test_input = torch.tensor([[6.0]], dtype=torch.float32)  # New input for prediction
    predicted = model(test_input)
    print(f'Predicted probability for input {test_input.item()}: {predicted.item():.4f}')
# This code implements a simple logistic regression model using PyTorch.
# It defines a neural network with a single linear layer and a sigmoid activation function.

Predicted probability for input 6.0: 0.3959


In [118]:
torch.tensor([[6.0]], dtype=torch.float32)

tensor([[6.]])

## Wine Dataset with PyTorch

In [119]:
import torch   
import torch.nn as nn
import torchvision
from torch.utils.data import DataLoader, Dataset
import numpy as np  
import pandas as pd
from sklearn.model_selection import train_test_split


In [120]:
class LettuceDataset(Dataset):
    def __init__(self, df):
        self.data = df.copy()
        features = self.data.iloc[:, :-1].apply(pd.to_numeric, errors='coerce').fillna(0).values
        self.x = torch.tensor(features, dtype=torch.float32)  # Features
        self.y = torch.tensor(self.data.iloc[:, -1].values, dtype=torch.long)  # Labels

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

In [121]:
df = pd.read_csv('data/vine_quality.csv', delimiter=',')
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4


In [122]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['quality'] = le.fit_transform(df['quality'])  # modifies labels in-place

# Check new labels:
print(sorted(df['quality'].unique()))

[0, 1, 2, 3, 4, 5]


In [123]:
dff = df.drop(df.columns[-1], axis=1) 
dataset = LettuceDataset(dff) 
x = dataset.x
y = dataset.y
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [124]:
input_size = x.shape[1]  # Number of input features columns


In [125]:
# classification nn.
import torch.nn.functional as F

class ClassificationNN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(ClassificationNN, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Example usage:
# input_dim = input_size (already defined)
# hidden_dim = 32 (example)
# output_dim = number of classes, e.g., 3 for 3-class classification
# model_cls = ClassificationNN(input_size, 32, 3)

In [126]:

# Should print [0, 1, 2, 3, 4, 5]


In [127]:
output_size = df['quality'].nunique()  # Number of unique classes in the target variable
hidden_dim = 32  # Example hidden layer size
model = ClassificationNN(input_size, hidden_dim, output_size)  # Linear model for regression


In [128]:
df['quality'].unique()

array([2, 3, 4, 1, 5, 0], dtype=int64)

In [129]:
criterian = nn.CrossEntropyLoss()  # Cross-Entropy Loss for multi-class classification
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), learning_rate)  # Stochastic Gradient Descent optimizer

In [130]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.2259,  0.1138, -0.1759,  0.0103, -0.2894,  0.1752,  0.0518,  0.0788,
          -0.2208, -0.2861,  0.2891],
         [ 0.0910,  0.2517, -0.1033, -0.1631,  0.1220, -0.2899, -0.0634,  0.1961,
           0.1593,  0.1486,  0.1505],
         [ 0.3011, -0.1007, -0.1791, -0.2480,  0.2540,  0.1029, -0.0978, -0.0687,
          -0.1973,  0.1232, -0.1870],
         [ 0.0097,  0.2213,  0.1400,  0.2504, -0.0965, -0.1608, -0.1466,  0.1497,
           0.2781, -0.0486, -0.2416],
         [-0.0746, -0.1955, -0.2214,  0.1092,  0.0909, -0.2063, -0.2116, -0.2136,
           0.0787,  0.2884, -0.1176],
         [ 0.2600,  0.2352,  0.3011, -0.2654, -0.0186, -0.0679,  0.1592, -0.2191,
           0.2072, -0.2810, -0.1156],
         [ 0.1234, -0.1961,  0.1461,  0.2881,  0.1138,  0.2396, -0.1185, -0.1778,
          -0.2333,  0.1508, -0.2938],
         [-0.1250,  0.0993, -0.1909,  0.2114, -0.1096, -0.2463,  0.1094, -0.0493,
          -0.1034,  0.1872,  0.0838],
         [-0.0098

In [131]:
num_epochs = 100
for epoch in range(num_epochs):
    # model
    y_hat = model(X_train)

    # loss
    loss = criterian(y_hat, y_train)

    # backpropagation
    loss.backward()

    #optimizer
    optimizer.step()
    optimizer.zero_grad()

    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')


Epoch [10/100], Loss: 1.3673
Epoch [20/100], Loss: 1.2987
Epoch [30/100], Loss: 1.2389
Epoch [40/100], Loss: 1.2122
Epoch [50/100], Loss: 1.1966
Epoch [60/100], Loss: 1.1868
Epoch [70/100], Loss: 1.1798
Epoch [80/100], Loss: 1.1750
Epoch [90/100], Loss: 1.1709
Epoch [100/100], Loss: 1.1674
